# This is a basic workflow to help you get started with Actions

name: CI
- nombre: configuración del entorno Node.js
  usos: acciones/setup-node@v2.5.1
  con:
    # Establecer autenticación siempre en npmrc
    always-auth: # opcional, el valor predeterminado es falso
    # Versión Especificación de la versión a usar. Ejemplos: 12.x, 10.15.1, >=10.15.0
    versión-nodo: # opcional
    # Archivo que contiene la versión Spec de la versión a usar. Ejemplos: .nvmrc, .node-version
    archivo-versión-nodo: # opcional
    # Arquitectura de destino para el uso de Node. Ejemplos: x86, x64. Utilizará la arquitectura del sistema de forma predeterminada.
    arquitectura: # opcional
    # Establezca esta opción si desea que la acción busque la última versión disponible que cumpla con las especificaciones de la versión
    comprobar-último: # opcional
    # Registro opcional para configurar la autenticación. Establecerá el registro en un archivo de nivel de proyecto .npmrc y .yarnrc, y configurará la autenticación para leer desde env.NODE_AUTH_TOKEN
    registro-url: # opcional
    # Ámbito opcional para autenticar contra registros de ámbito
    alcance: # opcional
    # Se usa para extraer distribuciones de nodos de versiones de nodos. Dado que existe un valor predeterminado, normalmente el usuario no lo proporciona.
    token: # opcional, el valor predeterminado es ${{ github.token }}
    # Se usa para especificar un administrador de paquetes para el almacenamiento en caché en el directorio predeterminado. Valores admitidos: npm, yarn, pnpm
    caché: # opcional
    # Se usa para especificar la ruta a un archivo de dependencia: package-lock.json, yarn.lock, etc. Admite comodines o una lista de nombres de archivo para almacenar en caché múltiples dependencias.
    ruta-dependencia-caché: # opcional
    # Obsoleto. Utilice la versión de nodo en su lugar. No será compatible después del 1 de octubre de 2019
    versión: # opcional
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

